## Pandas

- Pandas is a python library used for data manipulation and analysis
- Two key data structures are **series objects** and **dataframes**

Reference: 
- [online free docs](https://pandas.pydata.org/pandas-docs/stable/)
- [book old edition free](https://www.safaribooksonline.com/library/view/python-data-science/9781491912126/)
- [book new edition pay](https://smile.amazon.com/Python-Data-Science-Handbook-Essential/dp/1491912057/)

In [1]:
import numpy as np
import pandas as pd

# Series

In [2]:
# using a list
lst = [10,20,30]
ser = pd.Series(data=lst)
ser

0    10
1    20
2    30
dtype: int64

In [3]:
# specify the index label
lst = [10,20,30]
ser = pd.Series(data=lst, index=list('abc'))
ser

a    10
b    20
c    30
dtype: int64

In [4]:
# create a series using array
arr = np.array([100,200,300])
ser = pd.Series(arr)
ser

0    100
1    200
2    300
dtype: int64

In [5]:
# specify the index label
arr = np.array([100,200,300])
ser = pd.Series(data=arr, index=list('abc'))
ser

a    100
b    200
c    300
dtype: int64

In [6]:
# using a dictionary
dct = {'p':1000, 'q':2000, 'r':3000}
ser = pd.Series(data=dct)
ser

p    1000
q    2000
r    3000
dtype: int64

In [7]:
# naming the Series
ser = pd.Series(data = np.random.normal(size=3),
               index=list('abc'),
               name='X') # easy for concatinating a series to dataframe
ser

a   -0.124005
b   -0.054248
c   -1.094850
Name: X, dtype: float64

### Series Indexing & Slicing

In [8]:
ser = pd.Series(data = [10,20,30,40,50], index=list('abcde'))
ser

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [9]:
ser[2] # implicit indexing

30

In [10]:
ser['c'] # implicit indexing

30

In [11]:
ser.iloc[2] # explicit indexing using iloc -> index(#) location

30

In [12]:
ser.loc['c'] # explicit indexing using loc -> label location

30

# DataFrame


In [13]:
# nested list
lst = [[10,20,30],[40,50,60]]
df = pd.DataFrame(data = lst)
df

0   1   2
0  10  20  30
1  40  50  60

In [14]:
# labeling
lst = [[10,20,30],[40,50,60]]
df = pd.DataFrame(data = lst,
                 index=list('XY'),
                 columns=list('abc'))
df

a   b   c
X  10  20  30
Y  40  50  60

In [15]:
# 2 1d list (for columns)
lst1 = [10,20,30]
lst2 = [30,40,50]

df = pd.DataFrame(data={'X':lst1, 'Y':lst2}, index=list('abc'))
df

X   Y
a  10  30
b  20  40
c  30  50

In [16]:
# 2 dicitonaries
dct1 = {'aa':10,
       'bb':20,
       'cc':30}
dct2 = {'aa':100,
       'bb':200,
       'cc':300}
df = pd.DataFrame(data={'X':dct1, 'Y':dct2})
df

X    Y
aa  10  100
bb  20  200
cc  30  300

In [17]:
# 2 Series
ser1 = pd.Series(data=[10,20,30], index=['aa','bb','cc'])
ser2 = pd.Series(data=[100,200,300], index=['aa','bb','cc'])
df = pd.DataFrame(data={'X':ser1, 'Y':ser2})
df

X    Y
aa  10  100
bb  20  200
cc  30  300

## Attributes

In [18]:
np.random.seed(0)
df = pd.DataFrame(data= np.random.normal(size=(3,5)),
                 index=list('XYZ'),
                 columns=['aa','bb','cc','dd','ee'])
df

aa        bb        cc        dd        ee
X  1.764052  0.400157  0.978738  2.240893  1.867558
Y -0.977278  0.950088 -0.151357 -0.103219  0.410599
Z  0.144044  1.454274  0.761038  0.121675  0.443863

In [19]:
df.shape

(3, 5)

In [20]:
df.size

15

In [21]:
df.index

Index(['X', 'Y', 'Z'], dtype='object')

In [22]:
df.columns

Index(['aa', 'bb', 'cc', 'dd', 'ee'], dtype='object')

In [23]:
df.values

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773,  0.12167502,  0.44386323]])

In [24]:
df.head() # show top n (=5) rows

aa        bb        cc        dd        ee
X  1.764052  0.400157  0.978738  2.240893  1.867558
Y -0.977278  0.950088 -0.151357 -0.103219  0.410599
Z  0.144044  1.454274  0.761038  0.121675  0.443863

In [25]:
df.tail() # show bottom n (=5) rows

aa        bb        cc        dd        ee
X  1.764052  0.400157  0.978738  2.240893  1.867558
Y -0.977278  0.950088 -0.151357 -0.103219  0.410599
Z  0.144044  1.454274  0.761038  0.121675  0.443863

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, X to Z
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   aa      3 non-null      float64
 1   bb      3 non-null      float64
 2   cc      3 non-null      float64
 3   dd      3 non-null      float64
 4   ee      3 non-null      float64
dtypes: float64(5)
memory usage: 144.0+ bytes


In [27]:
df.describe()

aa        bb        cc        dd        ee
count  3.000000  3.000000  3.000000  3.000000  3.000000
mean   0.310273  0.934840  0.529473  0.753116  0.907340
std    1.378204  0.527224  0.599579  1.293350  0.831740
min   -0.977278  0.400157 -0.151357 -0.103219  0.410599
25%   -0.416617  0.675123  0.304840  0.009228  0.427231
50%    0.144044  0.950088  0.761038  0.121675  0.443863
75%    0.954048  1.202181  0.869888  1.181284  1.155711
max    1.764052  1.454274  0.978738  2.240893  1.867558

In [28]:
df.transpose() # = df.T

X         Y         Z
aa  1.764052 -0.977278  0.144044
bb  0.400157  0.950088  1.454274
cc  0.978738 -0.151357  0.761038
dd  2.240893 -0.103219  0.121675
ee  1.867558  0.410599  0.443863

In [29]:
df.T

X         Y         Z
aa  1.764052 -0.977278  0.144044
bb  0.400157  0.950088  1.454274
cc  0.978738 -0.151357  0.761038
dd  2.240893 -0.103219  0.121675
ee  1.867558  0.410599  0.443863

## DataFrame Indexing

In [30]:
np.random.seed(0)
df = pd.DataFrame(data= np.random.normal(size=(3,5)),
                 index=list('XYZ'),
                 columns=['aa','bb','cc','dd','ee'])
df

aa        bb        cc        dd        ee
X  1.764052  0.400157  0.978738  2.240893  1.867558
Y -0.977278  0.950088 -0.151357 -0.103219  0.410599
Z  0.144044  1.454274  0.761038  0.121675  0.443863

In [31]:
# indexing columns
df['aa']

X    1.764052
Y   -0.977278
Z    0.144044
Name: aa, dtype: float64

In [32]:
df[ ['aa','cc'] ] # passing a list, hence the double bracket

aa        cc
X  1.764052  0.978738
Y -0.977278 -0.151357
Z  0.144044  0.761038

In [33]:
df.loc['X']

aa    1.764052
bb    0.400157
cc    0.978738
dd    2.240893
ee    1.867558
Name: X, dtype: float64

In [34]:
df.iloc[0]

aa    1.764052
bb    0.400157
cc    0.978738
dd    2.240893
ee    1.867558
Name: X, dtype: float64

In [35]:
df.loc[['X','Y']]

aa        bb        cc        dd        ee
X  1.764052  0.400157  0.978738  2.240893  1.867558
Y -0.977278  0.950088 -0.151357 -0.103219  0.410599

In [36]:
# method 1 - chained
df['aa']['Z']

0.144043571160878

In [37]:
# method 2 - explicit
df['aa'].loc['Z']

0.144043571160878

In [38]:
# method 3 - loc (row first)
df.loc['Z','aa']

0.144043571160878

In [39]:
# multiple elements 
# method 1
df[['aa','cc']].loc[['X','Z']]

aa        cc
X  1.764052  0.978738
Z  0.144044  0.761038

In [40]:
# method 2 - loc
df.loc[['X','Z'],['aa','cc']]

aa        cc
X  1.764052  0.978738
Z  0.144044  0.761038

In [41]:
# method 3 - loc + chained
df.loc[['X','Z']][['aa','cc']]

aa        cc
X  1.764052  0.978738
Z  0.144044  0.761038

In [42]:
# type
type(df['aa'])

pandas.core.series.Series

In [43]:
type(df.loc['X'])

pandas.core.series.Series

In [44]:
# naming
df.index.names

FrozenList([None])

In [45]:
df.index.names = ['group']
df

aa        bb        cc        dd        ee
group                                                  
X      1.764052  0.400157  0.978738  2.240893  1.867558
Y     -0.977278  0.950088 -0.151357 -0.103219  0.410599
Z      0.144044  1.454274  0.761038  0.121675  0.443863

In [46]:
# reset the index  (not inplace)
df.reset_index()

group        aa        bb        cc        dd        ee
0     X  1.764052  0.400157  0.978738  2.240893  1.867558
1     Y -0.977278  0.950088 -0.151357 -0.103219  0.410599
2     Z  0.144044  1.454274  0.761038  0.121675  0.443863

In [47]:
# reset the index and DROP the original indexes (not inplace)
df.reset_index(drop=True)

aa        bb        cc        dd        ee
0  1.764052  0.400157  0.978738  2.240893  1.867558
1 -0.977278  0.950088 -0.151357 -0.103219  0.410599
2  0.144044  1.454274  0.761038  0.121675  0.443863

In [48]:
# original df not affected
df

aa        bb        cc        dd        ee
group                                                  
X      1.764052  0.400157  0.978738  2.240893  1.867558
Y     -0.977278  0.950088 -0.151357 -0.103219  0.410599
Z      0.144044  1.454274  0.761038  0.121675  0.443863

In [49]:
# reset the index and DROP the original indexes (not inplace)
df.reset_index(drop=True, inplace=True)
df

aa        bb        cc        dd        ee
0  1.764052  0.400157  0.978738  2.240893  1.867558
1 -0.977278  0.950088 -0.151357 -0.103219  0.410599
2  0.144044  1.454274  0.761038  0.121675  0.443863

In [50]:
# create new columns
df['new'] = list('PQR')
df

aa        bb        cc        dd        ee new
0  1.764052  0.400157  0.978738  2.240893  1.867558   P
1 -0.977278  0.950088 -0.151357 -0.103219  0.410599   Q
2  0.144044  1.454274  0.761038  0.121675  0.443863   R

In [51]:
# set the new column as an index
df.set_index('new',inplace=True)
df

aa        bb        cc        dd        ee
new                                                  
P    1.764052  0.400157  0.978738  2.240893  1.867558
Q   -0.977278  0.950088 -0.151357 -0.103219  0.410599
R    0.144044  1.454274  0.761038  0.121675  0.443863

In [52]:
# renaming index and columns
df.rename(index={'P':'XX','Q':'YY','R':'ZZ'},
         columns={'aa':'AA','bb':'BB'},
         inplace=True)
df

AA        BB        cc        dd        ee
new                                                  
XX   1.764052  0.400157  0.978738  2.240893  1.867558
YY  -0.977278  0.950088 -0.151357 -0.103219  0.410599
ZZ   0.144044  1.454274  0.761038  0.121675  0.443863

### Hierarchical Indexes

In [53]:
np.random.seed(0)
df = pd.DataFrame(
    data = np.random.randint(-100,100, (4,5)),
    index = pd.MultiIndex.from_product([['X','Y'],[1,2]]), # (x, y) * (1, 2) --> x1, x2, y1, y2
    columns = list('ABCDE'))
df

A   B   C   D   E
X 1  72 -53  17  92 -33
  2  95   3 -91 -79 -64
Y 1 -13 -30 -12  40 -42
  2  93 -61 -13  74 -12

In [54]:
df.loc['X']

A   B   C   D   E
1  72 -53  17  92 -33
2  95   3 -91 -79 -64

In [55]:
type(df.loc['X'])

pandas.core.frame.DataFrame

In [56]:
(df.loc['X'])['A']

1    72
2    95
Name: A, dtype: int64

In [57]:
(df.loc['X'])['A'].loc[1]

72

In [58]:
df.loc['X'].loc[1]['A']

72

In [59]:
df.index.names

FrozenList([None, None])

In [60]:
df.index.names = ['Group', 'Number']
df

A   B   C   D   E
Group Number                    
X     1       72 -53  17  92 -33
      2       95   3 -91 -79 -64
Y     1      -13 -30 -12  40 -42
      2       93 -61 -13  74 -12

### `xs`

In [61]:
# cross section indexing
df.xs('X', level='Group')

A   B   C   D   E
Number                    
1       72 -53  17  92 -33
2       95   3 -91 -79 -64

In [62]:
# e.g. accessing number 1 in both group
df.xs(1, level='Number')

A   B   C   D   E
Group                    
X      72 -53  17  92 -33
Y     -13 -30 -12  40 -42

## Append, Delete Rows/Columns From DataFrame

In [63]:
np.random.seed(0)
df1 = pd.DataFrame(data=np.random.normal(size=(2,3)))
df2 = pd.DataFrame(data=np.random.normal(size=(2,3)))

df1

0         1         2
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278

In [64]:
df2

0         1         2
0  0.950088 -0.151357 -0.103219
1  0.410599  0.144044  1.454274

In [65]:
df1.append(df2)

0         1         2
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278
0  0.950088 -0.151357 -0.103219
1  0.410599  0.144044  1.454274

In [66]:
df1 # not inplace

0         1         2
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278

In [67]:
df = df1.append(df2)
df # note indexes are maintained (0,1 from both dfs)

0         1         2
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278
0  0.950088 -0.151357 -0.103219
1  0.410599  0.144044  1.454274

In [68]:
df = df1.append(df2, ignore_index=True)
df

0         1         2
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278
2  0.950088 -0.151357 -0.103219
3  0.410599  0.144044  1.454274

In [69]:
np.random.seed(0)
df1 = pd.DataFrame(data=np.random.normal(size=(2,3)), index=['X','Y'], columns=['aa','bb','cc'])
df2 = pd.DataFrame(data=np.random.normal(size=(2,3)), index=['Z','W'], columns=['aa','bb','cc'])

df1

aa        bb        cc
X  1.764052  0.400157  0.978738
Y  2.240893  1.867558 -0.977278

In [70]:
df2

aa        bb        cc
Z  0.950088 -0.151357 -0.103219
W  0.410599  0.144044  1.454274

In [71]:
df1.append(df2)

aa        bb        cc
X  1.764052  0.400157  0.978738
Y  2.240893  1.867558 -0.977278
Z  0.950088 -0.151357 -0.103219
W  0.410599  0.144044  1.454274

In [72]:
df1.append(df2, ignore_index=True)

aa        bb        cc
0  1.764052  0.400157  0.978738
1  2.240893  1.867558 -0.977278
2  0.950088 -0.151357 -0.103219
3  0.410599  0.144044  1.454274

### appending a Series onto a DataFrame

In [73]:
np.random.seed(0)
df1 = pd.DataFrame(data=np.random.normal(size=(2,3)), index=['X','Y'], columns=['aa','bb','cc'])
ser = pd.Series(data=np.random.normal(size=3), index=['aa','bb','cc'], name='Z') # must be named
ser

aa    0.950088
bb   -0.151357
cc   -0.103219
Name: Z, dtype: float64

In [74]:
df1.append(ser) # name used as index name

aa        bb        cc
X  1.764052  0.400157  0.978738
Y  2.240893  1.867558 -0.977278
Z  0.950088 -0.151357 -0.103219

In [75]:
# missing values (NaN)
np.random.seed(0)
df1 = pd.DataFrame(data=np.random.normal(size=(2,3)), index=['X','Y'], columns=['aa','bb','cc'])
df2 = pd.DataFrame(data=np.random.normal(size=(2,3)), index=['Z','W'], columns=['aa','bb','dd'])
df1.append(df2)

aa        bb        cc        dd
X  1.764052  0.400157  0.978738       NaN
Y  2.240893  1.867558 -0.977278       NaN
Z  0.950088 -0.151357       NaN -0.103219
W  0.410599  0.144044       NaN  1.454274

In [76]:
np.random.seed(0)
df1 = pd.DataFrame(data=np.random.normal(size=(3,3)), index=list('XYZ'), columns=['aa','bb','cc'])
ser = pd.Series(data=[1000,2000,3000], index=list('XYZ')) # must be named
ser

X    1000
Y    2000
Z    3000
dtype: int64

In [77]:
df1

aa        bb        cc
X  1.764052  0.400157  0.978738
Y  2.240893  1.867558 -0.977278
Z  0.950088 -0.151357 -0.103219

In [78]:
df1['gg'] = ser
df1

aa        bb        cc    gg
X  1.764052  0.400157  0.978738  1000
Y  2.240893  1.867558 -0.977278  2000
Z  0.950088 -0.151357 -0.103219  3000

In [79]:
df1['aabb'] = df1['aa'] + df1['bb']
df1

aa        bb        cc    gg      aabb
X  1.764052  0.400157  0.978738  1000  2.164210
Y  2.240893  1.867558 -0.977278  2000  4.108451
Z  0.950088 -0.151357 -0.103219  3000  0.798731

In [80]:
# drop rows and columns
np.random.seed(0)
df = pd.DataFrame(data=np.random.normal(size=(3,5)), index=list('XYZ'), columns=['aa','bb','cc','dd','ee'])
df

aa        bb        cc        dd        ee
X  1.764052  0.400157  0.978738  2.240893  1.867558
Y -0.977278  0.950088 -0.151357 -0.103219  0.410599
Z  0.144044  1.454274  0.761038  0.121675  0.443863

In [81]:
# axis = 0 -> row
# axis = 1 -> columns
df.drop('X',axis=0) # not inplace

aa        bb        cc        dd        ee
Y -0.977278  0.950088 -0.151357 -0.103219  0.410599
Z  0.144044  1.454274  0.761038  0.121675  0.443863

In [82]:
df.drop('X',axis=0, inplace=True) # inplace
df

aa        bb        cc        dd        ee
Y -0.977278  0.950088 -0.151357 -0.103219  0.410599
Z  0.144044  1.454274  0.761038  0.121675  0.443863

In [83]:
df.drop(['aa','ee'],axis=1, inplace=True)
df

bb        cc        dd
Y  0.950088 -0.151357 -0.103219
Z  1.454274  0.761038  0.121675

In [84]:
# dropping dupliacte rows/columns
df = pd.DataFrame(data = [[1,2,3,4,5], [1,2,3,4,5], [10,20,30,40,50]],
                 index = list('XYZ'),
                 columns = list('ABCDE'))
df

A   B   C   D   E
X   1   2   3   4   5
Y   1   2   3   4   5
Z  10  20  30  40  50

In [85]:
df.drop_duplicates() # retain X drop Y

A   B   C   D   E
X   1   2   3   4   5
Z  10  20  30  40  50

In [86]:
df.drop_duplicates(keep = 'last') # retain Y instead of X

A   B   C   D   E
Y   1   2   3   4   5
Z  10  20  30  40  50

## Masking and Conditional Selecting

In [87]:
np.random.seed(0)
df = pd.DataFrame(data = np.random.randint(-100,100,(4,5)), index=list('WXYZ'), columns=list('ABCDE'))
df

A   B   C   D   E
W  72 -53  17  92 -33
X  95   3 -91 -79 -64
Y -13 -30 -12  40 -42
Z  93 -61 -13  74 -12

In [88]:
df > 0 # return boolean value in df

A      B      C      D      E
W   True  False   True   True  False
X   True   True  False  False  False
Y  False  False  False   True  False
Z   True  False  False   True  False

In [89]:
df[ df > 0 ] # return only where is True 

A    B     C     D   E
W  72.0  NaN  17.0  92.0 NaN
X  95.0  3.0   NaN   NaN NaN
Y   NaN  NaN   NaN  40.0 NaN
Z  93.0  NaN   NaN  74.0 NaN

In [90]:
df['D'] > 0 # only row X is False

W     True
X    False
Y     True
Z     True
Name: D, dtype: bool

In [91]:
df[df['D'] > 0] # masking row X out

A   B   C   D   E
W  72 -53  17  92 -33
Y -13 -30 -12  40 -42
Z  93 -61 -13  74 -12

In [92]:
df[df['D'] > 0]['B'] # showing only col B

W   -53
Y   -30
Z   -61
Name: B, dtype: int64

In [93]:
(df['D']>0) & (df['D']%4 == 0)

W     True
X    False
Y     True
Z    False
Name: D, dtype: bool

In [94]:
df[(df['D']>0) & (df['D']%4 == 0)]

A   B   C   D   E
W  72 -53  17  92 -33
Y -13 -30 -12  40 -42

Q: **Why not using `and` , `or` but `&` , `|`** ?

A: Not a single element , but a **Series** that is returning.<br>
Hence, we must use **SET OPERATION** type

## Missing Data
Pandas uses NaN (`np.NaN`) to denote missing value (NaT for datetime type)

In [95]:
ser = pd.Series(data = [1,2,3, None, 5, 6, np.NaN, 8], index=list('abcdefgh'))
ser

a    1.0
b    2.0
c    3.0
d    NaN
e    5.0
f    6.0
g    NaN
h    8.0
dtype: float64

In [96]:
# NaNs don't compare
ser == np.nan

a    False
b    False
c    False
d    False
e    False
f    False
g    False
h    False
dtype: bool

In [97]:
# use isna() instead
pd.isna(ser)

a    False
b    False
c    False
d     True
e    False
f    False
g     True
h    False
dtype: bool

In [98]:
# or notna() to check
pd.notna(ser)

a     True
b     True
c     True
d    False
e     True
f     True
g    False
h     True
dtype: bool

In [99]:
ser1 = pd.Series(data = [1,2,3, None, 5, 6, np.NaN, 8], index=list('abcdefgh'))
ser2 = pd.Series(data = [10,20,30,40,50,60,70,80], index=list('abcdefgh'))

In [100]:
ser1

a    1.0
b    2.0
c    3.0
d    NaN
e    5.0
f    6.0
g    NaN
h    8.0
dtype: float64

In [101]:
ser2

a    10
b    20
c    30
d    40
e    50
f    60
g    70
h    80
dtype: int64

In [102]:
# NaNs are contageous
ser1 + ser2 # d & g becomes NaN

a    11.0
b    22.0
c    33.0
d     NaN
e    55.0
f    66.0
g     NaN
h    88.0
dtype: float64

In [103]:
df1 = pd.DataFrame(data = [[1,2,3,None,5], [6, np.NaN, 8,9,10]], index=list('XY'), columns=list('abcde'))
df2 = pd.DataFrame(data = [[10,20,30,40,50], [60,70,80,90,100]], index=list('XY'), columns=list('abcde'))
df1

a    b  c    d   e
X  1  2.0  3  NaN   5
Y  6  NaN  8  9.0  10

In [104]:
df2

a   b   c   d    e
X  10  20  30  40   50
Y  60  70  80  90  100

In [105]:
df1 + df2

a     b   c     d    e
X  11  22.0  33   NaN   55
Y  66   NaN  88  99.0  110

In [106]:
# drop missing data
df = pd.DataFrame(data = [  [1,2,3,np.NaN,5],
                            [6,np.NaN,8,np.NaN,10],
                            [np.NaN,np.NaN,np.NaN,np.NaN,np.NaN],
                            [60,70,80,90,100]],
                  index = list('WXYZ'), columns = list('abcde'))
df

a     b     c     d      e
W   1.0   2.0   3.0   NaN    5.0
X   6.0   NaN   8.0   NaN   10.0
Y   NaN   NaN   NaN   NaN    NaN
Z  60.0  70.0  80.0  90.0  100.0

In [107]:
# drop rows with all nan 
df.dropna(axis=0, how='all')

a     b     c     d      e
W   1.0   2.0   3.0   NaN    5.0
X   6.0   NaN   8.0   NaN   10.0
Z  60.0  70.0  80.0  90.0  100.0

In [108]:
# drop rows with at least one nan
df.dropna(axis=0, how='any')

a     b     c     d      e
Z  60.0  70.0  80.0  90.0  100.0

In [109]:
# drop cols with at least 3 non-NaN values
df.dropna(axis=1, how='any', thresh=3)

a     c      e
W   1.0   3.0    5.0
X   6.0   8.0   10.0
Y   NaN   NaN    NaN
Z  60.0  80.0  100.0

In [110]:
# drop rows with at least 4 non-NaN values
df.dropna(axis=0, how='any', thresh=4)

a     b     c     d      e
W   1.0   2.0   3.0   NaN    5.0
Z  60.0  70.0  80.0  90.0  100.0

In [111]:
df

a     b     c     d      e
W   1.0   2.0   3.0   NaN    5.0
X   6.0   NaN   8.0   NaN   10.0
Y   NaN   NaN   NaN   NaN    NaN
Z  60.0  70.0  80.0  90.0  100.0

In [112]:
# fill the NaN value
df.fillna(0)

a     b     c     d      e
W   1.0   2.0   3.0   0.0    5.0
X   6.0   0.0   8.0   0.0   10.0
Y   0.0   0.0   0.0   0.0    0.0
Z  60.0  70.0  80.0  90.0  100.0

In [113]:
df.fillna(df.mean()) # columns-wise

a     b          c     d           e
W   1.000000   2.0   3.000000  90.0    5.000000
X   6.000000  36.0   8.000000  90.0   10.000000
Y  22.333333  36.0  30.333333  90.0   38.333333
Z  60.000000  70.0  80.000000  90.0  100.000000

In [114]:
df.fillna(value=df.mean()[['b','c']])

a     b          c     d      e
W   1.0   2.0   3.000000   NaN    5.0
X   6.0  36.0   8.000000   NaN   10.0
Y   NaN  36.0  30.333333   NaN    NaN
Z  60.0  70.0  80.000000  90.0  100.0

In [115]:
df['b'].fillna(value= df['b'].mean())

W     2.0
X    36.0
Y    36.0
Z    70.0
Name: b, dtype: float64

## Operation, Aggregation, UFuncs

### UFuncs

In [116]:
df = pd.DataFrame(data= np.random.randn(3,5), index=list('XYZ'), columns=list('abcde'))
df

a         b         c         d         e
X  1.125314 -0.358996  1.220608 -1.339496  0.428373
Y -0.123463  1.414377 -0.124051  2.008157  0.229887
Z  0.604894  1.627160  1.594561  0.230434 -0.064910

In [117]:
np.exp(df)

a         b         c         d         e
X  3.081185  0.698377  3.389248  0.261978  1.534759
Y  0.883854  4.113923  0.883335  7.449576  1.258457
Z  1.831058  5.089399  4.926164  1.259147  0.937151

In [118]:
np.sin(df * np.pi / 4)

a         b         c         d         e
X  0.773167 -0.278233  0.818424 -0.868435  0.330132
Y -0.096816  0.896076 -0.097275  0.999979  0.179573
Z  0.457412  0.957431  0.949728  0.179996 -0.050958

In [119]:
df = pd.DataFrame(data= np.ones((3,5)), index=list('XYZ'), columns=list('abcde'))
df

a    b    c    d    e
X  1.0  1.0  1.0  1.0  1.0
Y  1.0  1.0  1.0  1.0  1.0
Z  1.0  1.0  1.0  1.0  1.0

In [120]:
-df

a    b    c    d    e
X -1.0 -1.0 -1.0 -1.0 -1.0
Y -1.0 -1.0 -1.0 -1.0 -1.0
Z -1.0 -1.0 -1.0 -1.0 -1.0

In [121]:
df*10

a     b     c     d     e
X  10.0  10.0  10.0  10.0  10.0
Y  10.0  10.0  10.0  10.0  10.0
Z  10.0  10.0  10.0  10.0  10.0

In [122]:
ser1 = pd.Series(data=[10,20,30], index=list('abc'))
ser2 = pd.Series(data=[100,300,200], index=list('acb'))
ser1

a    10
b    20
c    30
dtype: int64

In [123]:
ser2

a    100
c    300
b    200
dtype: int64

In [124]:
ser1 + ser2

a    110
b    220
c    330
dtype: int64

In [125]:
ser1 = pd.Series(data=np.random.randint(-10,10,5), index=list('abcde'))
ser2 = pd.Series(data=np.random.randint(-15,15,5), index=list('cdefg'))
ser1

a     1
b     8
c    -8
d   -10
e   -10
dtype: int64

In [126]:
ser2

c   -11
d     6
e   -10
f    -9
g    -7
dtype: int64

In [127]:
ser1+ser2

a     NaN
b     NaN
c   -19.0
d    -4.0
e   -20.0
f     NaN
g     NaN
dtype: float64

In [128]:
df1 = pd.DataFrame(data=[[1,2,3,4],[5,6,7,8]], index=list('XY'), columns=list('abcd'))
df2 = pd.DataFrame(data=[[10,20,30,40],[50,60,70,80]], index=list('XY'), columns=list('abcd'))
df1

a  b  c  d
X  1  2  3  4
Y  5  6  7  8

In [129]:
df2

a   b   c   d
X  10  20  30  40
Y  50  60  70  80

In [130]:
df1+df2

a   b   c   d
X  11  22  33  44
Y  55  66  77  88

In [131]:
df1 = pd.DataFrame(data=np.random.randint(-10,10,(3,5)), index=list('XYZ'), columns=list('abcde'))
df2 = pd.DataFrame(data=np.random.randint(-15,15,(3,5)), index=list('WXY'), columns=list('cdefg'))
df1

a  b  c  d   e
X  7  5 -6 -1   0
Y -9 -9 -3 -1  -7
Z -4  1  4  8 -10

In [132]:
df2

c   d  e   f   g
W  -1 -12  6  -3  10
X  -5   5 -4 -11  -9
Y -11   0  5 -12  -3

In [133]:
df1+df2

a   b     c    d    e   f   g
W NaN NaN   NaN  NaN  NaN NaN NaN
X NaN NaN -11.0  4.0 -4.0 NaN NaN
Y NaN NaN -14.0 -1.0 -2.0 NaN NaN
Z NaN NaN   NaN  NaN  NaN NaN NaN

In [134]:
df1 = pd.DataFrame(data=np.random.randint(-10,10,(3,5)), index=list('XYZ'), columns=list('abcde'))
df2 = pd.DataFrame(data=np.random.randint(-15,15,(1,5)), index=list('X'), columns=list('cdefg'))
df1

a  b   c  d   e
X -6 -2   4  5  -7
Y  5  3   6  7  -5
Z -1 -7 -10 -5 -10

In [135]:
df2

c  d   e   f  g
X  2  3 -11 -13  1

In [136]:
df1+df2

a   b    c    d     e   f   g
X NaN NaN  6.0  8.0 -18.0 NaN NaN
Y NaN NaN  NaN  NaN   NaN NaN NaN
Z NaN NaN  NaN  NaN   NaN NaN NaN

In [137]:
df1 = pd.DataFrame(data=np.random.randint(-10,10,(3,5)), index=list('XYZ'), columns=list('abcde'))
df2 = pd.DataFrame(data=np.random.randint(-15,15,(3,1)), index=list('XYZ'), columns=list('c'))
df1

a  b   c  d  e
X -7 -8   0  3  6
Y -3 -1 -10  0  8
Z  1 -8  -8 -7 -7

In [138]:
df2

c
X   3
Y  -1
Z -12

In [139]:
df1+df2

a   b   c   d   e
X NaN NaN   3 NaN NaN
Y NaN NaN -11 NaN NaN
Z NaN NaN -20 NaN NaN

### Aggregation

In [140]:
df = pd.DataFrame(data=np.random.randn(3,5), index=list('XYZ'), columns=list('abcde'))
df

a         b         c         d         e
X -0.968980  0.027528  1.120605 -0.224039 -0.420183
Y  0.999830  0.431034 -0.650913 -1.498740 -1.230635
Z  0.194007 -0.998382 -0.367638  1.737199  0.593613

In [141]:
df.describe()

a         b         c         d         e
count  3.000000  3.000000  3.000000  3.000000  3.000000
mean   0.074952 -0.179940  0.034018  0.004807 -0.352402
std    0.989790  0.736947  0.951611  1.630063  0.914011
min   -0.968980 -0.998382 -0.650913 -1.498740 -1.230635
25%   -0.387487 -0.485427 -0.509275 -0.861390 -0.825409
50%    0.194007  0.027528 -0.367638 -0.224039 -0.420183
75%    0.596918  0.229281  0.376484  0.756580  0.086715
max    0.999830  0.431034  1.120605  1.737199  0.593613

In [142]:
print(df.count(axis=0)) # manipulate across rows, aggregation for each columns
print(df.count(axis=1)) # manipulate across columns, aggregation for each rows

a    3
b    3
c    3
d    3
e    3
dtype: int64
X    5
Y    5
Z    5
dtype: int64


In [143]:
print(df.sum(axis=0))
print(df.sum(axis=1))

a    0.224857
b   -0.539820
c    0.102054
d    0.014420
e   -1.057206
dtype: float64
X   -0.465069
Y   -1.949424
Z    1.158799
dtype: float64


In [144]:
print(df['a'].median())
print()
print(df.loc['X'].mean())
print()
print(df[['a','b']].corr())

0.1940071914439783

-0.09301388931392204

          a         b
a  1.000000  0.172091
b  0.172091  1.000000


In [145]:
# count unique

In [146]:
df = pd.DataFrame([[10,20,3,4,5],
                  [10,20,30,40,50],
                  [10,21,31,40,50],
                  [100,20,100,100,500]],
                 index=list('XYZW'),
                 columns=list('ABCDE'))
df

A   B    C    D    E
X   10  20    3    4    5
Y   10  20   30   40   50
Z   10  21   31   40   50
W  100  20  100  100  500

In [147]:
# unique value
df['A'].unique()

array([ 10, 100])

In [148]:
# number of unique number
df['A'].nunique()

2

In [149]:
# frequency table
df['A'].value_counts()

10     3
100    1
Name: A, dtype: int64

### Apply Method

In [150]:
df = pd.DataFrame([[10,20,3,4,'abc'],
                  [10,20,30,40,'abcd'],
                  [10,21,31,40,'abcde'],
                  [100,20,100,100,'abcdef']],
                 index=list('XYZW'),
                 columns=list('ABCDE'))
df

A   B    C    D       E
X   10  20    3    4     abc
Y   10  20   30   40    abcd
Z   10  21   31   40   abcde
W  100  20  100  100  abcdef

In [151]:
# square each element in col A
df['A'].apply(lambda x: x**2)

X      100
Y      100
Z      100
W    10000
Name: A, dtype: int64

In [152]:
# len for each element in col C
df['E'].apply(len)

X    3
Y    4
Z    5
W    6
Name: E, dtype: int64

### Sorting

In [153]:
df = pd.DataFrame(data= [[11,20,3,4,5],
                        [101,20,30,40,50],
                        [91,21,31,40,50],
                        [10,20,100,100,500]],
                 index=list('WXYZ'), columns=list('ABCDE'))
df

A   B    C    D    E
W   11  20    3    4    5
X  101  20   30   40   50
Y   91  21   31   40   50
Z   10  20  100  100  500

In [154]:
df.sort_values(by='A')

A   B    C    D    E
Z   10  20  100  100  500
W   11  20    3    4    5
Y   91  21   31   40   50
X  101  20   30   40   50

In [155]:
df.sort_values(by='X',axis=1)

B    C    D    E    A
W  20    3    4    5   11
X  20   30   40   50  101
Y  21   31   40   50   91
Z  20  100  100  500   10

In [156]:
ser = pd.Series(['George Chapman', 'John Cena', 'Terry Gilliam', 'Michael Palin', np.NaN])
ser

0    George Chapman
1         John Cena
2     Terry Gilliam
3     Michael Palin
4               NaN
dtype: object

In [157]:
ser.str.lower()

0    george chapman
1         john cena
2     terry gilliam
3     michael palin
4               NaN
dtype: object

In [158]:
ser.str.len()

0    14.0
1     9.0
2    13.0
3    13.0
4     NaN
dtype: float64

In [159]:
# regular expression (extract the first word)
ser.str.extract('([A-Za-z]+)')

0
0   George
1     John
2    Terry
3  Michael
4      NaN

In [160]:
# get the last word
ser.str.split().str.get(-1)

0    Chapman
1       Cena
2    Gilliam
3      Palin
4        NaN
dtype: object

# Group By
- automatically exclude NaN and NaT

In [161]:
df = pd.DataFrame(data={'Company':['Apple', 'Google', 'Microsoft', 'Apple', 'Google', 'Google', 'Microsoft'],
                  'Device':['phone', 'phone', 'laptop', 'laptop', 'phone', 'laptop', 'phone'],
                  'NumUnits':[10, 20, 30, 40, 50, 60, 70],
                  'DollarSales':[1000, 2000, 3000, 4000, 5000, 6000, 7000]})
df

Company  Device  NumUnits  DollarSales
0      Apple   phone        10         1000
1     Google   phone        20         2000
2  Microsoft  laptop        30         3000
3      Apple  laptop        40         4000
4     Google   phone        50         5000
5     Google  laptop        60         6000
6  Microsoft   phone        70         7000

In [162]:
df.groupby(by='Company').sum()

NumUnits  DollarSales
Company                         
Apple            50         5000
Google          130        13000
Microsoft       100        10000

In [163]:
df.groupby(by='Company').sum()['DollarSales']

Company
Apple         5000
Google       13000
Microsoft    10000
Name: DollarSales, dtype: int64

In [164]:
df.groupby(by='Company').describe()

NumUnits                                                      \
             count       mean        std   min   25%   50%   75%   max   
Company                                                                  
Apple          2.0  25.000000  21.213203  10.0  17.5  25.0  32.5  40.0   
Google         3.0  43.333333  20.816660  20.0  35.0  50.0  55.0  60.0   
Microsoft      2.0  50.000000  28.284271  30.0  40.0  50.0  60.0  70.0   

          DollarSales                                                    \
                count         mean          std     min     25%     50%   
Company                                                                   
Apple             2.0  2500.000000  2121.320344  1000.0  1750.0  2500.0   
Google            3.0  4333.333333  2081.665999  2000.0  3500.0  5000.0   
Microsoft         2.0  5000.000000  2828.427125  3000.0  4000.0  5000.0   

                           
              75%     max  
Company                    
Apple      3250.0  4000.0  
Google     5500.0  6000.0  
Microsoft  6000.0  7000.0

In [165]:
df.groupby(by=['Company','Device']).sum()

NumUnits  DollarSales
Company   Device                       
Apple     laptop        40         4000
          phone         10         1000
Google    laptop        60         6000
          phone         70         7000
Microsoft laptop        30         3000
          phone         70         7000

In [166]:
df.groupby(by=['Company','Device']).sum()['DollarSales']

Company    Device
Apple      laptop    4000
           phone     1000
Google     laptop    6000
           phone     7000
Microsoft  laptop    3000
           phone     7000
Name: DollarSales, dtype: int64

In [167]:
# use multiple aggregate function
df.groupby('Company').aggregate(np.sum) # = df.groupby(by='Company').sum()

NumUnits  DollarSales
Company                         
Apple            50         5000
Google          130        13000
Microsoft       100        10000

In [168]:
# multiple agg func
df.groupby('Company').aggregate([np.sum, np.mean])

NumUnits            DollarSales             
               sum       mean         sum         mean
Company                                               
Apple           50  25.000000        5000  2500.000000
Google         130  43.333333       13000  4333.333333
Microsoft      100  50.000000       10000  5000.000000

In [169]:
# agg funcs for different columns, respectively
df.groupby('Company').aggregate({'NumUnits':np.sum, 'DollarSales':np.mean})

NumUnits  DollarSales
Company                         
Apple            50  2500.000000
Google          130  4333.333333
Microsoft       100  5000.000000

In [170]:
df.groupby('Company').sum()

NumUnits  DollarSales
Company                         
Apple            50         5000
Google          130        13000
Microsoft       100        10000

In [171]:
# using groupby with filter
df.groupby('Company').filter(lambda x: x['DollarSales'].sum() > 7500)

Company  Device  NumUnits  DollarSales
1     Google   phone        20         2000
2  Microsoft  laptop        30         3000
4     Google   phone        50         5000
5     Google  laptop        60         6000
6  Microsoft   phone        70         7000

In [172]:
df.groupby('Company').mean()

NumUnits  DollarSales
Company                          
Apple      25.000000  2500.000000
Google     43.333333  4333.333333
Microsoft  50.000000  5000.000000

In [173]:
# use groupby with transform
# mean adjust
df.groupby('Company').transform(lambda x: x - x.mean())

NumUnits  DollarSales
0 -15.000000 -1500.000000
1 -23.333333 -2333.333333
2 -20.000000 -2000.000000
3  15.000000  1500.000000
4   6.666667   666.666667
5  16.666667  1666.666667
6  20.000000  2000.000000

In [174]:
# w/ apply
# self-defined function

def myFunc(x):
    x['NewCol'] = x['NumUnits'] / x['DollarSales'] - x['DollarSales'].mean()
    return x

df.groupby('Company').apply(myFunc)

Company  Device  NumUnits  DollarSales       NewCol
0      Apple   phone        10         1000 -2499.990000
1     Google   phone        20         2000 -4333.323333
2  Microsoft  laptop        30         3000 -4999.990000
3      Apple  laptop        40         4000 -2499.990000
4     Google   phone        50         5000 -4333.323333
5     Google  laptop        60         6000 -4333.323333
6  Microsoft   phone        70         7000 -4999.990000

# Pivot Table

In [175]:
df

Company  Device  NumUnits  DollarSales
0      Apple   phone        10         1000
1     Google   phone        20         2000
2  Microsoft  laptop        30         3000
3      Apple  laptop        40         4000
4     Google   phone        50         5000
5     Google  laptop        60         6000
6  Microsoft   phone        70         7000

In [176]:
df.pivot_table(index='Company',
              columns='Device',
              values='DollarSales')

Device     laptop  phone
Company                 
Apple        4000   1000
Google       6000   3500
Microsoft    3000   7000

In [177]:
df.pivot_table(index='Company',
              columns='Device',
              aggfunc={'DollarSales':np.sum,
                      'NumUnits':np.mean})

DollarSales       NumUnits      
Device         laptop phone   laptop phone
Company                                   
Apple            4000  1000       40    10
Google           6000  7000       60    35
Microsoft        3000  7000       30    70

In [178]:
df.pivot_table(index='Company',
              columns='Device',
              values='DollarSales',
              aggfunc=np.sum)

Device     laptop  phone
Company                 
Apple        4000   1000
Google       6000   7000
Microsoft    3000   7000

In [179]:
# include margins
df.pivot_table(index='Company',
              columns='Device',
              values='DollarSales',
              aggfunc=np.sum,
              margins=True)

Device     laptop  phone    All
Company                        
Apple        4000   1000   5000
Google       6000   7000  13000
Microsoft    3000   7000  10000
All         13000  15000  28000

# Concat, Merge

In [180]:
df1 = pd.DataFrame(np.arange(0,9).reshape(3,3),
                  index="R1 R2 R3".split(),
                  columns="C1 C2 C3".split())
df2 = pd.DataFrame(np.arange(10,19).reshape(3,3),
                  index="R4 R5 R6".split(),
                  columns="C1 C2 C3".split())
df1

C1  C2  C3
R1   0   1   2
R2   3   4   5
R3   6   7   8

In [181]:
df2

C1  C2  C3
R4  10  11  12
R5  13  14  15
R6  16  17  18

In [182]:
pd.concat([df1,df2], axis=1) # on col

C1   C2   C3    C1    C2    C3
R1  0.0  1.0  2.0   NaN   NaN   NaN
R2  3.0  4.0  5.0   NaN   NaN   NaN
R3  6.0  7.0  8.0   NaN   NaN   NaN
R4  NaN  NaN  NaN  10.0  11.0  12.0
R5  NaN  NaN  NaN  13.0  14.0  15.0
R6  NaN  NaN  NaN  16.0  17.0  18.0

In [183]:
pd.concat([df1,df2], axis=0) # on row

C1  C2  C3
R1   0   1   2
R2   3   4   5
R3   6   7   8
R4  10  11  12
R5  13  14  15
R6  16  17  18

In [184]:
df1 = pd.DataFrame(np.arange(0,9).reshape(3,3),
                  index="R1 R2 R3".split(),
                  columns="C1 C2 C3".split())
df2 = pd.DataFrame(np.arange(10,19).reshape(3,3),
                  index="R4 R5 R6".split(),
                  columns="C2 C3 C4".split())

pd.concat([df1, df2], axis=0) # row

C1  C2  C3    C4
R1  0.0   1   2   NaN
R2  3.0   4   5   NaN
R3  6.0   7   8   NaN
R4  NaN  10  11  12.0
R5  NaN  13  14  15.0
R6  NaN  16  17  18.0

In [185]:
df1 = pd.DataFrame(np.arange(0,9).reshape(3,3),
                  index="R1 R2 R3".split(),
                  columns="C1 C2 C3".split())
df2 = pd.DataFrame(np.arange(10,19).reshape(3,3),
                  index="R2 R3 R4".split(),
                  columns="C1 C2 C3".split())

pd.concat([df1, df2], axis=1) # row

C1   C2   C3    C1    C2    C3
R1  0.0  1.0  2.0   NaN   NaN   NaN
R2  3.0  4.0  5.0  10.0  11.0  12.0
R3  6.0  7.0  8.0  13.0  14.0  15.0
R4  NaN  NaN  NaN  16.0  17.0  18.0

In [186]:
# check duplicate column labels and indexs
# pd.concat([df1, df2], axis=1, verify_integrity=True) # show value error when there are duplicate

In [187]:
# ignore index
pd.concat([df1, df2], axis=1, ignore_index=True) # ignore and come up with default col label

0    1    2     3     4     5
R1  0.0  1.0  2.0   NaN   NaN   NaN
R2  3.0  4.0  5.0  10.0  11.0  12.0
R3  6.0  7.0  8.0  13.0  14.0  15.0
R4  NaN  NaN  NaN  16.0  17.0  18.0

In [188]:
df1 = pd.DataFrame(np.arange(0,9).reshape(3,3),
                  index="R1 R2 R3".split(),
                  columns="C1 C2 C3".split())
df2 = pd.DataFrame(np.arange(10,19).reshape(3,3),
                  index="R2 R3 R4".split(),
                  columns="C2 C3 C4".split())

In [189]:
pd.concat([df1,df2], axis=1) # join = outer

C1   C2   C3    C2    C3    C4
R1  0.0  1.0  2.0   NaN   NaN   NaN
R2  3.0  4.0  5.0  10.0  11.0  12.0
R3  6.0  7.0  8.0  13.0  14.0  15.0
R4  NaN  NaN  NaN  16.0  17.0  18.0

In [190]:
pd.concat([df1,df2], axis=1, join='inner') # inner join (drop nans)

C1  C2  C3  C2  C3  C4
R2   3   4   5  10  11  12
R3   6   7   8  13  14  15

In [191]:
# merge(join)
df1 = pd.DataFrame(data={'key':list('ABCD') ,
                        'value':np.random.randn(4)})
df2 = pd.DataFrame(data={'key':list('BDDE') ,
                        'value':np.random.randn(4)})
df1, df2

(  key     value
 0   A -0.542364
 1   B -1.719672
 2   C -0.578909
 3   D  1.426949,
   key     value
 0   B  0.276997
 1   D  0.789667
 2   D  0.322074
 3   E  0.700392)

In [192]:
# inner join
pd.merge(df1, df2, how='inner', on='key')

key   value_x   value_y
0   B -1.719672  0.276997
1   D  1.426949  0.789667
2   D  1.426949  0.322074

In [193]:
# outer join
pd.merge(df1, df2, how='outer', on='key')

key   value_x   value_y
0   A -0.542364       NaN
1   B -1.719672  0.276997
2   C -0.578909       NaN
3   D  1.426949  0.789667
4   D  1.426949  0.322074
5   E       NaN  0.700392

In [194]:
# left join
pd.merge(df1, df2, how='left', on='key')

key   value_x   value_y
0   A -0.542364       NaN
1   B -1.719672  0.276997
2   C -0.578909       NaN
3   D  1.426949  0.789667
4   D  1.426949  0.322074

In [195]:
# right join
pd.merge(df1, df2, how='right', on='key')

key   value_x   value_y
0   B -1.719672  0.276997
1   D  1.426949  0.789667
2   D  1.426949  0.322074
3   E       NaN  0.700392

In [196]:
idf2 = df2.set_index('key')
idf2

value
key          
B    0.276997
D    0.789667
D    0.322074
E    0.700392

In [197]:
pd.merge(df1, idf2, left_on='key', right_index=True,
         how='inner')

key   value_x   value_y
1   B -1.719672  0.276997
3   D  1.426949  0.789667
3   D  1.426949  0.322074

In [198]:
idf1 = df1.set_index('key')
idf1

value
key          
A   -0.542364
B   -1.719672
C   -0.578909
D    1.426949

In [199]:
pd.merge(idf1, idf2, left_index=True, right_index=True, how='inner')

value_x   value_y
key                    
B   -1.719672  0.276997
D    1.426949  0.789667
D    1.426949  0.322074

# Input/Output (IO)

In [200]:
# read csv
df = pd.read_csv('sample.txt', sep='|')
df

name  age gender
0    amy   10      f
1    bob   12      m
2  cathy   14      f
3   dave   11      m
4  ethan   13      m
5  fiona   10      f

In [201]:
df = pd.read_csv('sample.txt', sep='|', index_col=0)
df

age gender
name             
amy     10      f
bob     12      m
cathy   14      f
dave    11      m
ethan   13      m
fiona   10      f

In [202]:
df.to_csv('sample_new.txt')

In [203]:
df = pd.read_csv('sample.txt', sep='|')
df.to_csv('sample_new1.txt', index=False) # other wise the index will be returned

In [204]:
df = pd.read_csv('sample.txt', sep='|')
df.to_csv('sample_new2.txt', index=False, sep='|') # change the seperator

In [205]:
df.to_csv('sample.csv', index=False) # out put as csv flie

In [206]:
df = pd.read_csv('sample.csv')
df

name  age gender
0    amy   10      f
1    bob   12      m
2  cathy   14      f
3   dave   11      m
4  ethan   13      m
5  fiona   10      f

In [207]:
df = pd.read_excel('sample.xls', sheet_name='profile')
df

name  age gender
0    amy   10      f
1    bob   12      m
2  cathy   14      f
3   dave   11      m
4  ethan   13      m
5  fiona   10      f

In [208]:
df.to_excel('sample_new.xlsx', index=False)

# NumPy and Pandas Indexing Notes

https://numpy.org/doc/stable/user/basics.indexing.html?highlight=indexing


### Chain indexing `[m][n]` vs Multi-dimensional `[m, n]`


#### Caveat 1 - Indexing and Slicing:
  - They work differently.


In [209]:
arr = np.arange(1,40,2).reshape(4,5)
arr

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [210]:
# multi-D --> extracting elements
print(arr[1,2])

15


In [211]:
# chain indexing --> create (temporally) 1-d array --> then get the element at pos [2]
print(arr[1][2])

15


In [212]:
# in 2-D slices however may result differently
# multi-D --> only grabing the specified section
print(arr[0:3, 0:2])

[[ 1  3]
 [11 13]
 [21 23]]


In [213]:
# chained indexing
print(arr)
print()
print(arr[0:3]) # pick up first 3 rows
print()
print(arr[0:3][0:2]) # pick up first 2 rows

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]]

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


#### Caveat 2 - View vs Copy :
  - slices of array do not copy the internal array data but only product a new **view** of the original data
  - an explicit `.copy` is therefore recommended so you dont end up tempering with the original data

In [214]:
a = np.arange(1,40,2).reshape(4,5)
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]


In [215]:
b = a[0:3, 0:2]
print(b)

[[ 1  3]
 [11 13]
 [21 23]]


In [216]:
# update a
a[0,0] = 1000
# check a
print(a)
print()
# check b
print(b)

[[1000    3    5    7    9]
 [  11   13   15   17   19]
 [  21   23   25   27   29]
 [  31   33   35   37   39]]

[[1000    3]
 [  11   13]
 [  21   23]]


In [217]:
a = np.arange(1,40,2).reshape(4,5)
print(a)

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]]


In [218]:
b = a[0:3, 0:2].copy() # with copy # saved in a new location of memory
print(b)

[[ 1  3]
 [11 13]
 [21 23]]


In [219]:
# update a
a[0,0] = -1000
# check a
print(a)
print()
# check b
print(b)

[[-1000     3     5     7     9]
 [   11    13    15    17    19]
 [   21    23    25    27    29]
 [   31    33    35    37    39]]

[[ 1  3]
 [11 13]
 [21 23]]


### SettingWithCopyWarning :
#### Caveat 1:
- 
  



In [220]:
np.random.seed(0)
df = pd.DataFrame(np.random.normal(size=(4,6)),
                 index=list('wxyz'),
                 columns=list('abcdef'))
df

a         b         c         d         e         f
w  1.764052  0.400157  0.978738  2.240893  1.867558 -0.977278
x  0.950088 -0.151357 -0.103219  0.410599  0.144044  1.454274
y  0.761038  0.121675  0.443863  0.333674  1.494079 -0.205158
z  0.313068 -0.854096 -2.552990  0.653619  0.864436 -0.742165

In [221]:
# chain indexing get unpredictable result, cause we donno we're working on a view or copy
# therefore you dont know you're affecting the original data or not

df[df['f']>0]['b'] = -1000

# can't tell you whether you're working on a copy or original data

<ipython-input-221-c9e84907cc61>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['f']>0]['b'] = -1000


In [222]:
# fix: don't use chain indexing, use multi-d indexing instead
df.loc[df['f']>0, 'b'] = -1000

In [223]:
df

a            b         c         d         e         f
w  1.764052     0.400157  0.978738  2.240893  1.867558 -0.977278
x  0.950088 -1000.000000 -0.103219  0.410599  0.144044  1.454274
y  0.761038     0.121675  0.443863  0.333674  1.494079 -0.205158
z  0.313068    -0.854096 -2.552990  0.653619  0.864436 -0.742165

#### Caveat 2 -  :
  - View vs Copy
  - Make sure to work on the copy by specifying `.copy()`

In [224]:
np.random.seed(0)
df1 = pd.DataFrame(np.random.normal(size=(4,6)),
                 index=list('wxyz'),
                 columns=list('abcdef'))
df1

a         b         c         d         e         f
w  1.764052  0.400157  0.978738  2.240893  1.867558 -0.977278
x  0.950088 -0.151357 -0.103219  0.410599  0.144044  1.454274
y  0.761038  0.121675  0.443863  0.333674  1.494079 -0.205158
z  0.313068 -0.854096 -2.552990  0.653619  0.864436 -0.742165

In [225]:
df2 = df.loc['w':'y'] # getting a slice of df1
df2

a            b         c         d         e         f
w  1.764052     0.400157  0.978738  2.240893  1.867558 -0.977278
x  0.950088 -1000.000000 -0.103219  0.410599  0.144044  1.454274
y  0.761038     0.121675  0.443863  0.333674  1.494079 -0.205158

In [226]:
df2['a']['w'] = 100

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3331: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


In [227]:
# fix :
df2 = df.loc['w':'y'].copy() # get a copy
df2['a']['w'] = 100
df2

a            b         c         d         e         f
w  100.000000     0.400157  0.978738  2.240893  1.867558 -0.977278
x    0.950088 -1000.000000 -0.103219  0.410599  0.144044  1.454274
y    0.761038     0.121675  0.443863  0.333674  1.494079 -0.205158

#### indexing properly 

In [228]:
np.random.seed(0)
df = pd.DataFrame(np.random.normal(size=(4,6)),
                 index=list('wxyz'),
                 columns=list('abcdef'))
df

a         b         c         d         e         f
w  1.764052  0.400157  0.978738  2.240893  1.867558 -0.977278
x  0.950088 -0.151357 -0.103219  0.410599  0.144044  1.454274
y  0.761038  0.121675  0.443863  0.333674  1.494079 -0.205158
z  0.313068 -0.854096 -2.552990  0.653619  0.864436 -0.742165

In [229]:
# get row W
df.loc[['w'],:] # df.loc['w',:] will return Series object

a         b         c         d         e         f
w  1.764052  0.400157  0.978738  2.240893  1.867558 -0.977278

In [230]:
# get row x & y
df.loc[['x','y'],:]

a         b         c         d         e         f
x  0.950088 -0.151357 -0.103219  0.410599  0.144044  1.454274
y  0.761038  0.121675  0.443863  0.333674  1.494079 -0.205158

In [231]:
# get row w, x, y
df.loc['w':'y',:] # df.loc['w',:] will return Series object

a         b         c         d         e         f
w  1.764052  0.400157  0.978738  2.240893  1.867558 -0.977278
x  0.950088 -0.151357 -0.103219  0.410599  0.144044  1.454274
y  0.761038  0.121675  0.443863  0.333674  1.494079 -0.205158

In [232]:
df.loc[:,['a']]

a
w  1.764052
x  0.950088
y  0.761038
z  0.313068

In [233]:
# cols a & c
df.loc[:,['a','c']]

a         c
w  1.764052  0.978738
x  0.950088 -0.103219
y  0.761038  0.443863
z  0.313068 -2.552990

In [234]:
# cols a to c
df.loc[:,'a':'c']

a         b         c
w  1.764052  0.400157  0.978738
x  0.950088 -0.151357 -0.103219
y  0.761038  0.121675  0.443863
z  0.313068 -0.854096 -2.552990

In [235]:
# conditional selection
df.loc[:,'b'] < 0 # series

w    False
x     True
y    False
z     True
Name: b, dtype: bool

In [236]:
df.loc[:,['b']] < 0 # df

b
w  False
x   True
y  False
z   True

In [237]:
df.loc[ df.loc[:,'b'] < 0 , : ] # only take series

a         b         c         d         e         f
x  0.950088 -0.151357 -0.103219  0.410599  0.144044  1.454274
z  0.313068 -0.854096 -2.552990  0.653619  0.864436 -0.742165

# Handling Large File
- source: https://datacatalog.worldbank.org/dataset/education-statistics
- file EdStats.csv
  - 318 MB
  - 886931 rows * 70 columns

In [238]:
%%time
# vanilla, with no tricks
# if a file is zip, you don't need to unzip it
# use read_csv('Edstats_csv//EdStatsData.zip') instead

df = pd.read_csv('EdStatsData.csv')
df.head()

CPU times: user 7.73 s, sys: 3.76 s, total: 11.5 s
Wall time: 16.8 s


Country Name Country Code  \
0   Arab World          ARB   
1   Arab World          ARB   
2   Arab World          ARB   
3   Arab World          ARB   
4   Arab World          ARB   

                                      Indicator Name  Indicator Code  \
0  Adjusted net enrolment rate, lower secondary, ...      UIS.NERA.2   
1  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.F   
2  Adjusted net enrolment rate, lower secondary, ...  UIS.NERA.2.GPI   
3  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.M   
4  Adjusted net enrolment rate, primary, both sex...     SE.PRM.TENR   

        1970       1971       1972       1973       1974      1975  ...  2060  \
0        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
1        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
2        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
3        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
4  54.822121  54.894138  56.209438  57.267109  57.991138  59.36554  ...   NaN   

   2065  2070  2075  2080  2085  2090  2095  2100  Unnamed: 69  
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  

[5 rows x 70 columns]

In [239]:
%%time
# read only the first 10 rows

df = pd.read_csv('EdStatsData.csv', nrows=10)
df.head()

CPU times: user 20.1 ms, sys: 12.9 ms, total: 32.9 ms
Wall time: 35.3 ms


Country Name Country Code  \
0   Arab World          ARB   
1   Arab World          ARB   
2   Arab World          ARB   
3   Arab World          ARB   
4   Arab World          ARB   

                                      Indicator Name  Indicator Code  \
0  Adjusted net enrolment rate, lower secondary, ...      UIS.NERA.2   
1  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.F   
2  Adjusted net enrolment rate, lower secondary, ...  UIS.NERA.2.GPI   
3  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.M   
4  Adjusted net enrolment rate, primary, both sex...     SE.PRM.TENR   

        1970       1971       1972       1973       1974      1975  ...  2060  \
0        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
1        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
2        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
3        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
4  54.822121  54.894138  56.209438  57.267109  57.991138  59.36554  ...   NaN   

   2065  2070  2075  2080  2085  2090  2095  2100  Unnamed: 69  
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  

[5 rows x 70 columns]

In [240]:
%%time

# select only columns that I want
df = pd.read_csv('EdStatsData.csv', nrows=10,
                usecols = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1970', '1971'])
df.head()

CPU times: user 5.1 ms, sys: 3.88 ms, total: 8.98 ms
Wall time: 8.16 ms


Country Name Country Code  \
0   Arab World          ARB   
1   Arab World          ARB   
2   Arab World          ARB   
3   Arab World          ARB   
4   Arab World          ARB   

                                      Indicator Name  Indicator Code  \
0  Adjusted net enrolment rate, lower secondary, ...      UIS.NERA.2   
1  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.F   
2  Adjusted net enrolment rate, lower secondary, ...  UIS.NERA.2.GPI   
3  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.M   
4  Adjusted net enrolment rate, primary, both sex...     SE.PRM.TENR   

        1970       1971  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4  54.822121  54.894138

In [241]:
## some of these data may be to precise
# check the dtype first
df.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1970              float64
1971              float64
dtype: object

In [242]:
%%time
# memory efficient
# less precise () float64 -> float16

df = pd.read_csv('EdStatsData.csv', nrows=10,
                usecols = ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1970', '1971'],
                dtype={'1970':np.float16, '1971':np.float16})
df.head()


CPU times: user 7.85 ms, sys: 4.46 ms, total: 12.3 ms
Wall time: 14.9 ms


Country Name Country Code  \
0   Arab World          ARB   
1   Arab World          ARB   
2   Arab World          ARB   
3   Arab World          ARB   
4   Arab World          ARB   

                                      Indicator Name  Indicator Code     1970  \
0  Adjusted net enrolment rate, lower secondary, ...      UIS.NERA.2      NaN   
1  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.F      NaN   
2  Adjusted net enrolment rate, lower secondary, ...  UIS.NERA.2.GPI      NaN   
3  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.M      NaN   
4  Adjusted net enrolment rate, primary, both sex...     SE.PRM.TENR  54.8125   

       1971  
0       NaN  
1       NaN  
2       NaN  
3       NaN  
4  54.90625

In [243]:
%%time
import random

fname = 'EdStatsData.csv'
n = sum([1 for ln in open(fname)])-1   # -1 to account for header
s = n//5                              # sample only 20% of the file
skip = sorted(random.sample(range(1, n+1), n-s)) # get a list of random number of 1 - n+1 (%80 (n-s) of the data)
df = pd.read_csv(fname, skiprows=skip)

print(n, s, df.shape)
df.head()

886930 177386 (177386, 70)
CPU times: user 5.84 s, sys: 1.13 s, total: 6.97 s
Wall time: 9.47 s


Country Name Country Code  \
0   Arab World          ARB   
1   Arab World          ARB   
2   Arab World          ARB   
3   Arab World          ARB   
4   Arab World          ARB   

                                      Indicator Name      Indicator Code  \
0   Adjusted net enrolment rate, primary, female (%)      SE.PRM.TENR.FE   
1  Adjusted net intake rate to Grade 1 of primary...        UIS.NIRA.1.F   
2  Adult illiterate population, 15+ years, male (...    UIS.LP.AG15T99.M   
3  Adult literacy rate, population 15+ years, fem...   SE.ADT.LITR.FE.ZS   
4  Adult literacy rate, population 15+ years, gen...  UIS.LR.AG15T99.GPI   

        1970       1971       1972       1973       1974       1975  ...  \
0  43.351101  43.318150  44.640701  45.845718  46.449501  48.363892  ...   
1  44.342487  44.255711  44.446136  45.270443  46.171814  47.062019  ...   
2        NaN        NaN        NaN        NaN        NaN        NaN  ...   
3        NaN        NaN        NaN        NaN        NaN        NaN  ...   
4        NaN        NaN        NaN        NaN        NaN        NaN  ...   

   2060  2065  2070  2075  2080  2085  2090  2095  2100  Unnamed: 69  
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  

[5 rows x 70 columns]

In [244]:
%%time
# chunksize to read small size at a time

chunk_iter = pd.read_csv('EdStatsData.csv', chunksize=100000)

chunk_lst = []
for c in chunk_iter:
    # typically you won't append all of the c as shown below
    # instead, you will be doing a bunch of preprocessing (cleaning) work and the append the filtered version of c
    chunk_lst.append(c)

df = pd.concat(chunk_lst)

df.head()

CPU times: user 7.2 s, sys: 2.49 s, total: 9.69 s
Wall time: 12.8 s


Country Name Country Code  \
0   Arab World          ARB   
1   Arab World          ARB   
2   Arab World          ARB   
3   Arab World          ARB   
4   Arab World          ARB   

                                      Indicator Name  Indicator Code  \
0  Adjusted net enrolment rate, lower secondary, ...      UIS.NERA.2   
1  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.F   
2  Adjusted net enrolment rate, lower secondary, ...  UIS.NERA.2.GPI   
3  Adjusted net enrolment rate, lower secondary, ...    UIS.NERA.2.M   
4  Adjusted net enrolment rate, primary, both sex...     SE.PRM.TENR   

        1970       1971       1972       1973       1974      1975  ...  2060  \
0        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
1        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
2        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
3        NaN        NaN        NaN        NaN        NaN       NaN  ...   NaN   
4  54.822121  54.894138  56.209438  57.267109  57.991138  59.36554  ...   NaN   

   2065  2070  2075  2080  2085  2090  2095  2100  Unnamed: 69  
0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
1   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
2   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
3   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  
4   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN          NaN  

[5 rows x 70 columns]

# Exercise

pandas is a python library used for data manipulation and analysis; it has two key data structures - series objects and dataframes

#### Exercise Set 1
Create a pd dataframe as below:
> `np.random.seed(10) df = pd.DataFrame(` <br>
 `np.random.randint(18, 100, size=(7,5)),` <br>
 `columns=['age', 'conversations', 'friends', 'unk1’, 'unk2'])` <br>
 `df`

In [245]:
import pandas as pd
import numpy as np

In [246]:
np.random.seed(10)
df = pd.DataFrame(np.random.randint(18, 100, size=(7,5)),
                  columns=['age', 'conversations', 'friends', 'unk1', 'unk2'])
df

age  conversations  friends  unk1  unk2
0   27             33       82    46    47
1   26             91       18    58    54
2   34             29       72    80    51
3   90             96       67    69    72
4   95             87       31    43    31
5   48             48       30    83    49
6   75             54       45    36    95

##### Questions
1. print the conversations column
2. print the age and conversations column
3. print row 2
4. print rows 0 and 2
5. print element at row 2 and conversations column - using chained indexing
6. print element at row 2 and conversations column - using multi-dimensional indexing
7. print elements at row 0 and row 2 and age column and conversation column - using chained indexing
8. print elements at row 0 and row 2 and age column and conversation column - using multi-dimensional indexing

In [247]:
# 1. print the conversations column
df['conversations']

0    33
1    91
2    29
3    96
4    87
5    48
6    54
Name: conversations, dtype: int64

In [248]:
# 2. print the age and conversations column
df[['age','conversations']]

age  conversations
0   27             33
1   26             91
2   34             29
3   90             96
4   95             87
5   48             48
6   75             54

In [249]:
# 3. print row 2
df.loc[2]

age              34
conversations    29
friends          72
unk1             80
unk2             51
Name: 2, dtype: int64

In [250]:
# 4. print rows 0 and 2
df.loc[[0,2]]

age  conversations  friends  unk1  unk2
0   27             33       82    46    47
2   34             29       72    80    51

In [251]:
# 5. print element at row 2 and conversations column - using chained indexing
df.iloc[2]['conversations']

29

In [252]:
# 6. print element at row 2 and conversations column - using multi-dimensional indexing
df.loc[2,'conversations']

29

In [253]:
# 7. print elements at row 0 and row 2 and age column and conversation column - using chained indexing

df.iloc[[0,2]][['age','conversations']]

age  conversations
0   27             33
2   34             29

In [254]:
# 8. print elements at row 0 and row 2 and age column and conversation column - using multi-dimensional indexing
df.loc[[0,2], ['age','conversations']]

age  conversations
0   27             33
2   34             29

##### Question
Drop columns `friends`, `unk1` and `unk2` (so `df` no longer has these columns)
- how would you do this with using inplace?
- how would you do this without using inplace?

In [255]:
df.drop(['friends','unk1','unk2'], axis=1, inplace=True)

##### Question
Create a new column called `age-group` and set it to age//10
- how would you do this without using apply and lambda?
- how would you do this with using apply and lambda?
- how would you do this with using apply and a custom function?

In [256]:
# do this without using apply and lambda
df['age-group'] = df['age']//10
df

age  conversations  age-group
0   27             33          2
1   26             91          2
2   34             29          3
3   90             96          9
4   95             87          9
5   48             48          4
6   75             54          7

In [257]:
# do this with using apply and lambda
df['age-group'] = df['age'].apply(lambda x: x//10)
df

age  conversations  age-group
0   27             33          2
1   26             91          2
2   34             29          3
3   90             96          9
4   95             87          9
5   48             48          4
6   75             54          7

In [258]:
# do this with using apply and a custom function
def myFunc(x):
    return x//10
df['age-group'] = df['age'].apply(myFunc)
df

age  conversations  age-group
0   27             33          2
1   26             91          2
2   34             29          3
3   90             96          9
4   95             87          9
5   48             48          4
6   75             54          7

##### Question
Create a new column called 'gender' in df with the following values:
- ['male', 'male', 'female', 'female', 'female', 'male', 'male']

In [259]:
df['gender'] = ['male', 'male', 'female', 'female', 'female', 'male', 'male']
df

age  conversations  age-group  gender
0   27             33          2    male
1   26             91          2    male
2   34             29          3  female
3   90             96          9  female
4   95             87          9  female
5   48             48          4    male
6   75             54          7    male

##### Question
Return all samples in df that are male **and** have > 50 conversations

In [260]:
df[(df['gender']=='male') & (df['conversations'] > 50)]

age  conversations  age-group gender
1   26             91          2   male
6   75             54          7   male

##### Question
Return all samples in df that are female **or** have age > 40

In [261]:
df[(df['gender'] == 'female') | (df['age']>40)]

age  conversations  age-group  gender
2   34             29          3  female
3   90             96          9  female
4   95             87          9  female
5   48             48          4    male
6   75             54          7    male

##### Question
Create new dataframe called dfnew which has the same data as df. Then set the element at index 3 and column gender to MALE.
- while ensuring df doesn't change
- and while ensuring you don't get the `SettingWithCopyWarning`

In [262]:
dfnew = df.copy()
dfnew.loc[3,'gender'] = 'male'
df

age  conversations  age-group  gender
0   27             33          2    male
1   26             91          2    male
2   34             29          3  female
3   90             96          9  female
4   95             87          9  female
5   48             48          4    male
6   75             54          7    male

In [263]:
dfnew

age  conversations  age-group  gender
0   27             33          2    male
1   26             91          2    male
2   34             29          3  female
3   90             96          9    male
4   95             87          9  female
5   48             48          4    male
6   75             54          7    male

### Exercise Set 2
Create a pd dataframe as below:
>`np.random.seed(0)` <br>
 `ser1 = np.random.randint(-100, 100, 5)` <br>
 `ser2 = ser1 + np.random.random(5)` <br>
 `df = pd.DataFrame({'true':ser1, 'pred':ser2})` <br>
 `df` <br>


In [264]:
np.random.seed(0)
ser1 = np.random.randint(-100, 100, 5)
ser2 = ser1 + np.random.random(5)
df = pd.DataFrame({'true':ser1, 'pred':ser2})
df

true       pred
0    72  72.857946
1   -53 -52.152748
2    17  17.623564
3    92  92.384382
4   -33 -32.702465

##### Question
Create a new column with the squared error (`(true - pred)^2`). <br>
Then find mean squared error between true and predicted values.

In [265]:
df['sqr'] = pow(df['true'] - df['pred'], 2)
df['sqr'].mean()

0.4158028029226076

### Exercise Set 3
Read kaggle train.csv data into dataframe called titanic

In [266]:
titanic = pd.read_csv('train.csv')
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

##### Question
Create a copy of titanic and put it in a dataframe called df

In [267]:
df = titanic.copy()
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

##### Question
- Get the column names of df (columns) 
- Get the #rows, #cols of df (shape)
- Get info on df (info())
- Get basic stats on df (describe())

In [268]:
print(df.columns)
print()
print(df.shape)
print()
print(df.info())
df.describe()

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

(891, 12)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

##### Question
The Cabin column on it's own isn't useful... but the Deck (1st character in Cabin) might be. <br>
Use apply and a custom function to create a Deck column.
- Your custom function will need to handle NaN values in Cabin (pd.notna(x))
- Once done, use conditional selection with masking to look at a sample of rows where Cabin is not NaN to check transformation

In [269]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [270]:
def getFirstS(x):
    if pd.isna(x) is True:
        return x
    else:
        return(x[0])

df['Deck'] = df['Cabin'].apply(getFirstS)
df[pd.notna(df['Cabin']) == True]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
10            11         1       3   
11            12         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked Deck  
1        0  PC 17599  71.2833          C85        C    C  
3        0    113803  53.1000         C123        S    C  
6        0     17463  51.8625          E46        S    E  
10       1   PP 9549  16.7000           G6        S    G  
11       0    113783  26.5500         C103        S    C  
..     ...       ...      ...          ...      ...  ...  
871      1     11751  52.5542          D35        S    D  
872      0       695   5.0000  B51 B53 B55        S    B  
879      1     11767  83.1583          C50        C    C  
887      0    112053  30.0000          B42        S    B  
889      0    111369  30.0000         C148        C    C  

[204 rows x 13 columns]

##### Question
The Name column on its own isn't useful... but the Title (2nd word in Name) might be. <br>
Use apply and a custom function to create a Title column.
- Your custom function will need to handle NaN values in Name
- Once done, use conditional selection with masking to look at a sample of rows where Name is not NaN to check transformation

In [271]:
def getTitle(x):
    if pd.notna(x) == True:
        return x.split()[1].strip()
    else:
        return x

df['Title'] = df['Name'].apply(getTitle)
df[pd.notna(df['Name']) == True]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked Deck  Title  
0        0         A/5 21171   7.2500   NaN        S  NaN    Mr.  
1        0          PC 17599  71.2833   C85        C    C   Mrs.  
2        0  STON/O2. 3101282   7.9250   NaN        S  NaN  Miss.  
3        0            113803  53.1000  C123        S    C   Mrs.  
4        0            373450   8.0500   NaN        S  NaN    Mr.  
..     ...               ...      ...   ...      ...  ...    ...  
886      0            211536  13.0000   NaN        S  NaN   Rev.  
887      0            112053  30.0000   B42        S    B  Miss.  
888      2        W./C. 6607  23.4500   NaN        S  NaN  Miss.  
889      0            111369  30.0000  C148        C    C    Mr.  
890      0            370376   7.7500   NaN        Q  NaN    Mr.  

[891 rows x 14 columns]

##### Question
Get the frequency distribution of the various Titles.

In [272]:
df['Title'].value_counts()

Mr.             502
Miss.           179
Mrs.            121
Master.          40
Dr.               7
Rev.              6
y                 4
Planke,           3
Impe,             3
Col.              2
Mlle.             2
Major.            2
Gordon,           2
Mulder,           1
Mme.              1
Melkebeke,        1
Carlo,            1
Ms.               1
Don.              1
der               1
Messemaeker,      1
Capt.             1
Cruyssen,         1
Walle,            1
Pelsmaeker,       1
Jonkheer.         1
the               1
Velde,            1
Billiard,         1
Steen,            1
Shawah,           1
Name: Title, dtype: int64

##### Question
Drop the following columns from df ['Name', 'Ticket', 'Cabin’]

In [273]:
df.drop(['Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

In [274]:
df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0            1         0       3    male  22.0      1      0   7.2500   
1            2         1       1  female  38.0      1      0  71.2833   
2            3         1       3  female  26.0      0      0   7.9250   
3            4         1       1  female  35.0      1      0  53.1000   
4            5         0       3    male  35.0      0      0   8.0500   

  Embarked Deck  Title  
0        S  NaN    Mr.  
1        C    C   Mrs.  
2        S  NaN  Miss.  
3        S    C   Mrs.  
4        S  NaN    Mr.

In [275]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         2
Deck           687
Title            0
dtype: int64

##### Question
Get the amount of missing data for each column (percentage)

In [276]:
df.isna().mean()

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Sex            0.000000
Age            0.198653
SibSp          0.000000
Parch          0.000000
Fare           0.000000
Embarked       0.002245
Deck           0.771044
Title          0.000000
dtype: float64

##### Question
Let's take care of missing Age data.


Let's create a new imputed column called impAge, which replaces missing Age values with mean of Age.

In [277]:
df['impAge'] = df['Age'].fillna(df['Age'].mean())
df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare  \
0            1         0       3    male  22.0      1      0   7.2500   
1            2         1       1  female  38.0      1      0  71.2833   
2            3         1       3  female  26.0      0      0   7.9250   
3            4         1       1  female  35.0      1      0  53.1000   
4            5         0       3    male  35.0      0      0   8.0500   

  Embarked Deck  Title  impAge  
0        S  NaN    Mr.    22.0  
1        C    C   Mrs.    38.0  
2        S  NaN  Miss.    26.0  
3        S    C   Mrs.    35.0  
4        S  NaN    Mr.    35.0

##### Question
Let's take care of missing Embarked data
- Get the frequency distribution of Embarked

In [278]:
df['Embarked'].value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

##### Question
Use masking with conditional selection to examine the rows in df which have Embarked=Nan

In [279]:
df[df['Embarked'].isna()]

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  Fare Embarked  \
61            62         1       1  female  38.0      0      0  80.0      NaN   
829          830         1       1  female  62.0      0      0  80.0      NaN   

    Deck  Title  impAge  
61     B  Miss.    38.0  
829    B   Mrs.    62.0

##### Question
We could just drop the rows with missing Embarked data (how would you do this?)...
but instead, let's create a new imputed column called impEmbarked, which replaces missing Embarked values with 'X’.

In [280]:
df['impEmbarked'] = df['Embarked'].fillna('X')
df['impEmbarked'].value_counts()

S    644
C    168
Q     77
X      2
Name: impEmbarked, dtype: int64

##### Question
Similarly, let's create a new imputed column called impDeck, which replaces missing Deck values with 'X'

In [281]:
df['impDeck'] = df['Deck'].fillna('X')
df['impDeck'].value_counts()

X    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: impDeck, dtype: int64